---
title: "measured."
description: |
  A one-time trophy bitch screams into the void.
author: 
  - name: Charles T. Gray
    url: https://twitter.com/cantabile
    affiliation: R-Ladies
    affiliation_url: https://rladies.org/
site: radix::radix_website
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

What if one practices mathematical science like music?

My goal is to spend four hours a day on *work with intent*[^1].

[^1]: This term is adopted from a piano teacher that I studied under, that I subsequently adapted into my own teaching. She encouraged me to *practice with intent*; that is, play what you intend to play. I found this to be particularly useful for discouraging my students, and myself, from the age-old pitfall of playing a piece of music until you make a mistake and stopping and playing that section over until you get it right. It's better to play *through* the piece, which empowers you to adapt to mistakes you will inevitably play and, most importantly, not lose time. Oddly, it appeared to be a universal misconception, myself included, that without careful consideration, the attempt to *get the notes right* inevitably means the **rhythm is wrong**, and thus you get nothing right after all. Best, therefore, to play through the piece.    

```{r get data, echo=TRUE}
# packages
library(tidyverse)

# get data
tracker_data <- readr::read_csv("") %>%
  # tidy up columns
  rename(start = `Start time`,
         end = `End time`,
         duration = Duration,
         hours = `Duration in hours`,
         category = Category,
         project = `Task name`) %>%
  # drop things unused features
  select(-`Task description`, -Note) %>% 
  # convert dates to date objects in R
  mutate(start = lubridate::dmy_hm(start),
         end = lubridate::dmy_hm(end),
         duration = lubridate::as.duration(duration),
         day = lubridate::day(start),
         month = lubridate::month(start, label = TRUE, abbr = FALSE) %>% 
           fct_drop(), # drop month levels with no values 
         date = lubridate::date(start),
         category = map_chr(category, .f = function(x) {
           switch(x,
                  "Research" = "research",
                  "Busywork" = "busywork",
                  "Skills" = "skills",
                  "Wellness" = "wellness",
                  x)
         })) 

```

### for each month, how many hours a day?

```{r echo=TRUE}
# plot monthly distributions
tracker_data %>% 
  filter(category != "wellness") %>%  # for now, need to join in calendar and munge yoga
  group_by(date, month) %>% 
  summarise(time = sum(duration) / 3600) %>%
  filter(time != 0) %>% 
   ggplot(aes(x = time)) +
  geom_vline(xintercept = 4, linetype = "dotted") +
  geom_histogram(bins = 5) +
  facet_grid(month ~ .) 

```

## for each month how many hours a day for each category? 


```{r echo=TRUE}
# plot monthly by category distributions
tracker_data %>% 
  group_by(date, category, month) %>% 
  summarise(time = sum(duration) / 3600) %>%
  filter(category != "wellness", time != 0) %>%  # for now, need to join in calendar and munge yoga
  ggplot(aes(x = time)) +
  geom_vline(xintercept = 1.3, linetype = "dotted") +
  geom_histogram(bins = 10) +
  facet_grid(month ~ category)

```


## over time? 


```{r echo=TRUE}
wes_palette = "Moonrise2"
point_alpha = 0.6
point_size = 3

# plot monthly by category distributions
tracker_data %>% 
  filter(category != "wellness") %>%  # for now, need to join in calendar and munge yoga
  group_by(day, month) %>% 
  summarise(time = sum(duration) / 3600) %>% 
  mutate(goal = time  > 4) %>% 
  ggplot(aes(x = day, y = time)) +
  geom_line() +
  geom_point(aes(colour = goal), alpha = point_alpha, size = point_size) +
  scale_color_manual(values=wesanderson::wes_palette(n=2, name= wes_palette)) +
  geom_hline(yintercept = 4, linetype = "dotted") +
  facet_grid(month ~ .) 

# with categories
tracker_data %>% 
  filter(category != "wellness") %>%  # for now, need to join in calendar and munge yoga
  group_by(day, month, category) %>% 
  summarise(time = sum(duration) / 3600) %>% 
  mutate(goal = time  > 1.3) %>% 
  ggplot(aes(x = day, y = time)) +
  geom_line() +
  geom_point(aes(colour = goal), alpha = point_alpha, size = point_size / 1.5) +
  scale_color_manual(values=wesanderson::wes_palette(n=2, name= wes_palette)) +
  geom_hline(yintercept = 1.3, linetype = "dotted") +
  facet_grid(month ~ category) 


```


## my system

I use a combination of gtd, pomodoros, and bullet journaling in my productivity system.

And a toy elephant, along with a [digraph](https://en.wikipedia.org/wiki/Directed_graph).


***

*Work in progress.*
