---
title: "the letter there's no point sending"
description: |
  I don't have the time for people who think that expressing distress at bullying and tenancy eviction means I am mentally deficient and cannot make decisions for myself. 
author:
  - name: Charles T. Gray
    url: https://twitter.com/cantabile
date: 02-11-2019
output:
  radix::radix_article:
    self_contained: false
categories:
  - grrr...
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Dear `<sadly not just one person>`,

I appreciate you do not understand my anger and that you believe yourself to be "just trying to be nice".

Here's the thing, you've spoken about me behind my back and made decisions for me, after I reported to you distress at being bullied and harassed, whilst being evicted from my rental property. I believe anyone would be distressed under these conditions. But you seem to have inferred all sorts of bewildering things about my mental capacity.

Reporting this distress does not mean I abdicated my ability to reason as to what I am capable of doing and what will be of most benefit to my wellbeing. In all cases, the decisions made for me without consultation or warning were not only contrary to what would have actually assisted me, but compounded assumptions about me in others who look to you as role models. This leads to further bullying and discriminatory experiences for me where yet more people believe they can make decisions for me without consulting me and be disingenuous in their dealings with me. I believe this to be textbook discriminatory behaviour. 

You cannot understand why I act angrily when you attempt well meant gestures and act dismissively when I try to broach this subject. 

However, I am trying to understand how you can think what I feel are hateful things about my capacity as a functioning human being. If you truly don't feel I can think for myself, then you see me as lesser to you. I don't find your nice gestures to make up for this; I feel strongly that I am cast in a pantomime where you pretend nothing happened so you don't have to feel bad about anything.

Every time you contact me with your nice gestures, you remind me of what horrible things you think of me. It's hurtful, and I don't feel respected when you dismiss my offense so brusquely. I feel trivialised as irrational or, shrugs, I can only guess as you will not explain your actions. 

Meanwhile, I'm thinking, when will it happen again? When will you lie to me again? When will you interfere in my research and make decisions for me again? I am _scared_ of you, and what you believe of me, and I am deeply offended, not only for myself but for anyone you perceive to be different in this way you encounter in future. Who will learn from you that this is an acceptable way to treat someone?  

I don't see a functional relationship between us while you believe I can't reason for myself or that you do not need to be truthful with me. I don't understand your nice gestures. It's not nice or respectful to treat someone like this, and trying to pretend nothing happened is not being nice to me. It's being nice to you. I don't have any reason to be nice to you while you think these things of me. 

You said you don't have time for this. Good lord, I don't have time for people who think it's respectful to interact with me like this. So would you, please, stop wasting mine?

Goodbye,

Just someone who has a different disposition to you

## postscript

Just in case you're reading this wondering, well, that's all well and good, but what do you think should be done instead, here you go:

1. Acknowledge that the way you treated me was discriminatory. We're all capable of discriminatory behaviours and unconcious bias, it's not doing it that's the problem, it's how you handle it when you're called out that defines you.  
2. Ditch all disingenuousness. Ask yourself why you think it's okay to hide information or lie to me. Ask yourself whether you would be okay with someone making these assumptions about your reasoning capability. 
3. Enough with the victim blaming. Just how much am I meant to withstand with perfect poise? Would you?
4. Stop pretending it's nice to pretend nothing happened. When someone raises these issues with you, they're usually concerned the behaviour is going to continue. When you pretend nothing happened the implict message is that the distress we began with has been deemed trivial by you and that you believe your past behaviour to be respectful. Therefore there is no trust that behaviours will not be repeated. Instead, apologise and reassure the person that you respect them, that you will not remove their agency again, and that you have learnt from the experience.  
